import { SkillTree, SkillType } from '@/types';

export const skillTreeBard: SkillTree = {
  id: 35,
	name: "Bard",
	description: "Bard Skill Planner",
	backgroundImage: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2Fbard_background.png?alt=media&token=f210b976-7e4f-4fad-b09a-4a9223555582",
	type: "Archetype",
  skills: [
    {
      id: 1,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FWip1%20-%20Bard.png?alt=media&token=45da2580-a731-46d4-b2bd-eb7ebda341df",
      name: "WIP (Work In Progress)",
      description: "WIP (Work In Progress)",
      isActiveSkill: false,
      isStartSkill: false,
      nivel: 1,
      cooldown: 90,
      range: 0,
      cost: 1,
      manaCost: 50,
      skillPreview: "",
      line: 0,
      position: 4,
      castTime: 8.7,
      isDefaultActive: false,
      costToActive: 10,
      skillTreeId: 35,
      createdAt: "2024-08-01T15:30:29.835Z",
      updatedAt: "2024-08-03T22:40:47.047Z",
      EffectSkills: [],
      chooseableSkills: []
    },
    {
      id: 2,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/MageV1%2FSkillSelectIcon.png?alt=media&token=5e929306-20bf-46dd-9d5f-d404415c2f93",
      name: "Skill Selection",
      description: "Skill Selection",
      isActiveSkill: true,
      isStartSkill: true,
      nivel: 0,
      cooldown: 0,
      range: 0,
      cost: 1,
      manaCost: 0,
      skillPreview: "",
      line: 10,
      position: 5,
      castTime: 0,
      isDefaultActive: false,
      costToActive: 0,
      skillTreeId: 35,
      createdAt: "2024-08-01T23:07:10.400Z",
      updatedAt: "2024-08-03T22:38:00.600Z",
      EffectSkills: [],
      chooseableSkills: [
        {
          id: 14,
          image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FInstrument_Flute_Icon.png?alt=media&token=ebf6b4df-6577-4478-a2f9-ac555917517f",
          name: "Instrument Flute",
          description: "Passive Effect or Ability Type",
          isActiveSkill: false,
          isStartSkill: false,
          nivel: 0,
          cooldown: 0,
          range: 0,
          cost: 1,
          manaCost: 0,
          skillPreview: "",
          line: 10,
          position: 5,
          castTime: 0,
          isDefaultActive: false,
          costToActive: 0,
          skillTreeId: 35,
          createdAt: "2024-08-01T23:07:10.400Z",
          updatedAt: "2024-08-03T22:38:00.600Z",
          EffectSkills: [],
          chooseableSkills: [],
        },
        {
          id: 15,
          image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FInstrument_Fiddle_Icon.png?alt=media&token=0df32068-d8a6-4ace-9589-c069f305b400",
          name: "Instrument Fiddle",
          description: "Passive Effect or Ability Type",
          isActiveSkill: false,
          isStartSkill: false,
          nivel: 0,
          cooldown: 0,
          range: 0,
          cost: 1,
          manaCost: 0,
          skillPreview: "",
          line: 10,
          position: 5,
          castTime: 0,
          isDefaultActive: false,
          costToActive: 0,
          skillTreeId: 35,
          createdAt: "2024-08-01T23:07:10.400Z",
          updatedAt: "2024-08-03T22:38:00.600Z",
          EffectSkills: [],
          chooseableSkills: [],
        },
        {
          id: 16,
          image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FInstrument_Drum_Icon.png?alt=media&token=8842ba30-deb5-4b1b-871a-b78a646fc121",
          name: "Instrument Drum",
          description: "Passive Effect or Ability Type",
          isActiveSkill: false,
          isStartSkill: false,
          nivel: 0,
          cooldown: 0,
          range: 0,
          cost: 1,
          manaCost: 0,
          skillPreview: "",
          line: 10,
          position: 5,
          castTime: 0,
          isDefaultActive: false,
          costToActive: 0,
          skillTreeId: 35,
          createdAt: "2024-08-01T23:07:10.400Z",
          updatedAt: "2024-08-03T22:38:00.600Z",
          EffectSkills: [],
          chooseableSkills: [],
        }
      ]
    },
    {
      id: 3,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FDark_Lullaby.png?alt=media&token=c56582ba-bb2b-4872-a79a-7b02c80730ab",
      name: "Dark Lullaby",
      description: "Deal(50-100%) spirit damage to target enemy each second(scales in power over the course of the cast). This damage will not wake an Incapacitated target.<br/> <br/>The final hit applies Stunned for 6 seconds if the target is Incapacitated.",
      isActiveSkill: true,
      isStartSkill: true,
      nivel: 1,
      cooldown: 25,
      range: 30,
      cost: 1,
      manaCost: 25,
      skillPreview: "",
      line: 5,
      position: 8,
      castTime: 3,
      isDefaultActive: false,
      costToActive: 4,
      skillTreeId: 35,
      createdAt: "2024-08-01T21:11:33.434Z",
      updatedAt: "2024-08-03T22:40:15.373Z",
      EffectSkills: [],
      chooseableSkills: []
    },
    {
      id: 4,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FResonant%20Weapon.png?alt=media&token=7b039709-df99-48db-af28-567eef2f6c00",
      name: "Resonant Weapon",
      description: "Your weapon combo finishers trigger additional effects based on your active music.<br/><br/>Menacing<br/>Deal bonus(75%) arcane damage and apply Weakened to each target hit.<br/><br/>Cathartic<br/>Deal bonus(75%) bleed damage and apply Wounded to each target hit.<br/><br/>Cheerful<br/>Heal a nearby injured ally for (250%)(healing). Favors yourself and party members.<br/><br/>Pensive<br/>Restore mana to a nearby ally in need equal to 25 + (5%) magical power. Favors yourself and party members.<br/><br/>Epic<br/>Dispel up to 1 root and apply Pep to each party member.",
      isActiveSkill: false,
      isStartSkill: false,
      nivel: 0,
      cooldown: 0,
      range: 0,
      cost: 1,
      manaCost: 0,
      skillPreview: "",
      line: 6,
      position: 5,
      castTime: 0,
      isDefaultActive: false,
      costToActive: 4,
      skillTreeId: 35,
      createdAt: "2024-08-01T21:37:09.449Z",
      updatedAt: "2024-08-03T22:40:25.955Z",
      EffectSkills: [],
      chooseableSkills: []
    },
    {
      id: 5,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FMaddening%20Dance.png?alt=media&token=830ac58b-3071-4705-b9ff-7564bcdc4f0d",
      name: "Maddening Dance",
      description: "Damage nearby enemies for (40%) arcane damage every second. Damage increases with less targets, up to (60%) arcane damage.<br/><br/>Applies Humiliated to targets that are Demoralized.",
      isActiveSkill: true,
      isStartSkill: false,
      nivel: 0,
      cooldown: 25,
      range: 5,
      cost: 1,
      manaCost: 25,
      skillPreview: "",
      line: 8,
      position: 1,
      castTime: 4,
      isDefaultActive: false,
      costToActive: 0,
      skillTreeId: 35,
      createdAt: "2024-08-01T21:56:30.930Z",
      updatedAt: "2024-08-03T22:38:16.652Z",
      EffectSkills: [],
      chooseableSkills: [],
    },
    {
      id: 6,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FGet_Off_The_Stage.png?alt=media&token=06e729c7-6241-4095-b40b-18bda13b49bb",
      name: "Get Off The Stage",
      description: "Knockback enemies in front of you with your instrument, dealing (175%) bludgeon damage and applying 3 stacks of Snared that tapers off over the course of 6 seconds. Also applies Disarmed to targets with Staggered.",
      isActiveSkill: true,
      isStartSkill: false,
      nivel: 0,
      cooldown: 25,
      range: 5,
      cost: 1,
      manaCost: 25,
      skillPreview: "",
      line: 8,
      position: 4,
      castTime: 4,
      isDefaultActive: false,
      costToActive: 0,
      skillTreeId: 35,
      createdAt: "2024-08-01T22:07:54.884Z",
      updatedAt: "2024-08-03T22:38:19.259Z",
      EffectSkills: [],
      chooseableSkills: []
    },
    {
      id: 57,
      image: "https://firebasestorage.googleapis.com/v0/b/emporium-of-verra.appspot.com/o/BardV1%2FDiscordance.png?alt=media&token=977433c9-b274-4a3c-8aac-1e43099074de",
      name: "Discordance",
      description: "Launch a wild burst of 3 discordant notes at your target, each dealing (75%🢆) arcane damage and applying Staggered. The notes will bounce to random nearby enemies dealing reduced damage.",
      isActiveSkill: true,
      isStartSkill: false,
      nivel: 0,
      cooldown: 25,
      range: 30,
      cost: 1,
      manaCost: 20,
      skillPreview: "",
      line: 8,
      position: 5,
      castTime: 1.2,
      isDefaultActive: false,
      costToActive: 0,
      skillTreeId: 35,
      createdAt: "2024-08-01T22:10:23.824Z",
      updatedAt: "2024-08-03T22:38:20.962Z",
      EffectSkills: [],
      chooseableSkills: []
    }  
  ],
  SkillConnection: [],
  combos: [],
  createdAt: '',
  updatedAt: '',
}
  
